'use strict';
/*----------------------------------------------------------------*/
/* Configs
/*----------------------------------------------------------------*/
var utils = require('./utils');
var display = utils.display();
var git = require('./git');
var path = require('path');

// #TODO check for bower.json file
try {
    var bowerJson = require(utils.projectPath('bower.json'));

} catch (e) {
    bowerJson = {};
}
try {
    var packJson = require(utils.projectPath('package.json'));
} catch (e) {
    packJson = {};
}

var config = packJson.config || bowerJson.config || {};

exports.main = packJson.main || bowerJson.main; // #TODO show error if is missing
exports.name = packJson.name || bowerJson.name;
exports.version = packJson.version || bowerJson.version;
exports.repository = packJson.repository || bowerJson.repository;

if (bowerJson.main) {
    var mainJSFile = utils.bowerMainJs(exports.main); //;
}

if (exports.repository && exports.repository.url) {
    var repository = exports.repository; // #TODO show warning if is missing
} else {
    // Find repo in .git/config
    var gitUrl = git.originUrl();

    // Only use SSH repos.
    if (gitUrl && gitUrl.match(/^ssh/)) {
        exports.repository = { url: gitUrl };
    }

    //utils.display().warn('bower.json is missing repository url! Please update it to ' + gitUrl + '\n');
}

exports.paths = utils.extend({
    scripts: './scripts',
    docs: './docs',
    reports: './reports',
    target: './dist',
    media: './media',
    templates: './templates',
    components: './components',
    styles: './styles',
    test: './test',
    index: './index.dev.html',
    routes: {

    }
}, config.paths || {});

// RAML api configuration
exports.data = utils.extend({
    route: '',
    useApiVersion: false,
    files: [
        './**/services/**/*.raml',
        './**/raml/**/*.raml',
        '!./**/node_modules/**/+(examples|example|test)/**'
    ]
}, config.data);

exports.proxies = utils.extend({
    // TO BE REMOVED AFTER MIGRATION ON THE NEW RAML STRUCTURE
    '/api': 'http://localhost:3030/',
    '/services/rest': 'http://localhost:3030/'
}, config.proxies || {});

exports.eslint = config.eslint;
exports.karma = config.karma;

exports.tests = {
    requestInternalRegExp: /(?:\.\.\/){2}scripts\//,
    includeInternalRegExp: /^(?!.*(?:node_modules|bower_components)).*\.spec(?:\.js)?$/
};

exports.server = {
    port: null // generated by browsersync
};
exports.build = {
    all: false // pack all external dependencies // see externals in webpack config
};

// override the main entry point to use separate sources entry for build
// and use main property from package for distribution
exports.entry = (function() {
    if (! utils.isUndefined(exports.main)) {
        var output = {
                name: path.normalize(utils.bowerMainJs(exports.main).replace('./src', './')),
                path: exports.main
            }
            // in webpack you need to add './' on the entry
            // https://github.com/webpack/webpack/issues/1908
        if (!utils.startsWith(output.path, '.', 0)) {
            output.path = './' + output.path;
        }
        if (!utils.isUndefined(config.entry)) {
            output = utils(config.entry).map(function(k, v) {
                return {
                    name: v + '.js',
                    path: k
                }
            }).head();
        }
        return output;
    }
})();
